apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: network
spec:
  interval: 10m
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/svm-k8s-lab/network/nginx
  prune: true
  wait: false
  dependsOn:
    - name: namespaces
  targetNamespace: network
  postBuild:
    substitute:
      namespace_name: network
