controller:
  serviceAccount:
    create: false
    name: nginx-sa
  ingressClassResource:
    name: nginx-main
  ingressClass: nginx-main
  service:
    annotations:
      io.cilium/lb-ipam-ips: "10.123.44.212"
    type: LoadBalancer