apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/postgres-grafana
patches:
  - path: patches.yaml
    target:
      kind: Cluster
      name: grafana-postgres
