apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/cnpg-operator
patches:
  - path: patches.yaml
    target:
      kind: HelmRelease
      name: cnpg-operator
