apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bases
  namespace: flux-system
spec:
  interval: 5m
  serviceAccountName: kustomize-controller 
  wait: true
  prune: true
  path: ./infrastructure/base
  sourceRef:
    kind: GitRepository
    name: flux-system
