apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: network
resources:
  - ./nginx/hr.yaml
  - ./nginx/rbac.yaml


configMapGenerator:
  - name: nginx-values
    options:
      disableNameSuffixHash: true
    namespace: network          
    files:
      - values.yaml=./nginx/values.yaml
