apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/network/nginx
patches:
  - path: patches.yaml
    target:
      kind: HelmRelease
      name: nginx-main
