apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-grafana
  namespace: database
spec:
  interval: 10m
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/svm-k8s-lab/monitoring/cnpg-grafana
  prune: true
  wait: true
  dependsOn:
    - name: namespaces
    - name: cnpg-operator
  targetNamespace: database
  postBuild:
    substitute:
      namespace_name: database
